
language: android
android:
   components:
     - build-tools-26.0.2
     - android-26
     - sys-img-armeabi-v7a-android-tv-l
     - add-on
     - extra
   licenses:
     - 'android-sdk-preview-license-52d11cd2'
     - 'android-sdk-license-.+'
     - 'google-gdk-license-.+'

jdk: oraclejdk8

notifications:
  email: true

sudo: required #The build runs out of memory and is killed if we use the container system

script:
  - ./gradlew clean build
